import Link from "next/link";
import { I } from "@/components/icons/Icons";
import { LaunchNotifySignup } from "@/components/geo/LaunchNotifySignup";
import { pageMetadata } from "@/lib/page-metadata";

/**
 * /launch-notify — dedicated landing page for the proactive Tier-2
 * "notify me when you launch" signup (Task #3 sub-item 4b —
 * docs/GEO_LAUNCH_POLICY.md §4).
 *
 * Why a dedicated page in addition to the /pricing embed:
 *   - A permalink we can paste into emails/Slack when someone asks "when
 *     will you launch in [country]?" — the /pricing embed is buried mid-page.
 *   - A terminal URL for the checkout-defer flow: if a Tier-2 visitor is
 *     turned away at checkout and wants to share the waitlist with a
 *     colleague, they can hand over this URL rather than the scroll-depth
 *     anchor on /pricing.
 *   - Lets PM A/B-test dedicated-page framing against the pricing-embed
 *     framing by directing ads to different `source` values —
 *     `launch_notify_page` vs `pricing_country_picker` shows the split
 *     in `geo_waitlist.source`.
 *
 * Source attribution:
 *   - The component is rendered with `source="launch_notify_page"`. That
 *     literal is pinned by scripts/test-geo-waitlist.mjs so PM's analytics
 *     queries keep working across refactors.
 *
 * Rendering model:
 *   - This page is a plain server component (no `"use client"` — the
 *     interactive bit lives inside `LaunchNotifySignup`). A bare
 *     /launch-notify hit serves the empty-picker shell just like
 *     /pricing. With a `?country=XX` query string (Task #3 sub-item 4c,
 *     for campaign-email hot-links), Next 14 renders dynamically at
 *     request time and hands us `searchParams.country`, which we pass
 *     through `pickCountry()` and feed into `LaunchNotifySignup`'s
 *     `defaultCountry` prop. The component's internal sanitiser drops
 *     anything that isn't a current Tier-2 ISO code, so a bad param
 *     (Tier-1 code, Tier-3 code, gibberish, repeated array value)
 *     just falls back to the empty picker — no misleading preselect.
 *   - Still no `CF-IPCountry` server-side read; auto-detection from the
 *     request geography would turn every hit dynamic even without a
 *     query param, and campaign hot-links cover the "preselect when
 *     we already know the country" use case. Can add later as a
 *     server-component wrapper if the signal justifies it.
 *
 * SEO posture:
 *   - `robots: { index: false, follow: true }` — this is a utility
 *     signup page, not a page we want Google to rank against "pdfcraftai
 *     pricing" or "pdfcraftai [country]". `follow: true` so outbound
 *     links on the page (privacy, /register for Tier-1 visitors who
 *     landed here by mistake) still transfer their signal.
 *   - The canonical path is set anyway so that if someone does deep-link
 *     with a tracking query string, search engines collapse to the bare
 *     URL.
 */

export const metadata = pageMetadata({
  title: "Launch waitlist — pdfcraftai.com",
  description:
    "Not in a supported region yet? Tell us your country and we'll email you the moment pdfcraftai.com launches there. One email only, no newsletter.",
  canonical: "/launch-notify",
  og: {
    title: "Be the first to know when pdfcraftai.com launches in your country",
    description:
      "Pick your country. We'll email you once, the moment we go live there. No newsletter, no spam.",
  },
  // Utility page — we don't want this competing with pricing / home in
  // search. Links (privacy policy, /register) still transfer signal via
  // follow:true. See the pageMetadata docstring for why this goes here
  // instead of being a separate `export const robots`.
  robots: { index: false, follow: true },
});

/**
 * Pull an ISO-3166 alpha-2 code out of a raw `searchParams.country`
 * value without assuming it's a single string.
 *
 * Next.js hands `searchParams` back as `string | string[] | undefined`
 * per query key — a repeated `?country=DE&country=FR` comes through as
 * an array. We take the first entry in that case, because:
 *   - A link generated by a campaign tool should only ever set the
 *     key once; an array means someone hand-edited the URL or an
 *     overzealous redirect doubled the param.
 *   - Picking the first preserves "whatever the original campaign
 *     tool intended" even if a later layer tacked on a second value.
 *   - LaunchNotifySignup's `defaultCountry` sanitiser will drop the
 *     value anyway if it isn't a real Tier-2 code — this function
 *     only needs to coerce the raw shape down to a single string; it
 *     doesn't need to validate against the Tier-2 set (defense in
 *     depth: if either layer is ever bypassed, the other still holds).
 *
 * Anything that isn't a non-empty string becomes undefined → the
 * component renders with its empty-picker default. No `?country=` on
 * the URL means the user sees the empty picker just like before.
 */
function pickCountry(
  raw: string | string[] | undefined
): string | undefined {
  const first = Array.isArray(raw) ? raw[0] : raw;
  if (typeof first !== "string") return undefined;
  const trimmed = first.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

export default function LaunchNotifyPage({
  searchParams,
}: {
  // Next 14 provides searchParams to server-rendered page components.
  // Reading it opts the page into dynamic rendering at request time
  // (which is what we want — a bare /launch-notify still serves, but
  // /launch-notify?country=DE renders on-demand with DE preselected).
  searchParams?: { country?: string | string[] };
}) {
  // `defaultCountry` is best-effort: LaunchNotifySignup runs the Tier-2
  // sanitiser internally (garbage / Tier-1 / Tier-3 / "XX" fall through
  // to an empty picker), so the user never sees a misleading preselect
  // for a country we haven't actually opted them into.
  const defaultCountry = pickCountry(searchParams?.country);

  return (
    <main>
      {/* ===== Hero ===== */}
      <section style={{ paddingTop: 96, paddingBottom: 40 }}>
        <div
          className="container-x"
          style={{ padding: "0 28px", maxWidth: 780, textAlign: "center" }}
        >
          <div
            className="eyebrow"
            style={{
              marginBottom: 12,
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
            }}
          >
            <I.Globe size={14} />
            LAUNCH WAITLIST
          </div>
          <h1
            style={{
              fontSize: 48,
              letterSpacing: "-0.03em",
              lineHeight: 1.08,
              margin: 0,
            }}
          >
            We&apos;ll email you the moment we launch in your country.
          </h1>
          <p
            className="muted"
            style={{
              fontSize: 18,
              maxWidth: 620,
              margin: "20px auto 0",
              lineHeight: 1.55,
            }}
          >
            pdfcraftai.com rolls out country-by-country as local tax and
            compliance work finishes. Tell us where you are and we&apos;ll
            send exactly one email — the day we go live there.
          </p>
        </div>
      </section>

      {/* ===== Signup card ===== */}
      <section style={{ paddingTop: 8 }}>
        <div
          className="container-x"
          style={{ padding: "0 28px", maxWidth: 780 }}
        >
          <LaunchNotifySignup
            source="launch_notify_page"
            defaultCountry={defaultCountry}
            heading="Which country are you in?"
            subheading="Pick your country. We'll email you the moment we launch there. One email, no newsletter."
          />
        </div>
      </section>

      {/* ===== Promise strip (what this waitlist actually is) ===== */}
      <section style={{ paddingTop: 64 }}>
        <div
          className="container-x"
          style={{ padding: "0 28px", maxWidth: 960 }}
        >
          <div className="eyebrow" style={{ marginBottom: 8, textAlign: "center" }}>
            WHAT YOU&apos;RE SIGNING UP FOR
          </div>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
              gap: 14,
              marginTop: 20,
            }}
          >
            <PromiseCard
              icon="Bell"
              title="One email, then silence"
              body="You'll get exactly one message — the day pdfcraftai.com goes live in your country. We don't add you to a newsletter, digest, or product announcement list."
            />
            <PromiseCard
              icon="Lock"
              title="Your address doesn't go anywhere else"
              body="We store your email, country, and the date you signed up. That's it. No profile enrichment, no ad retargeting, no third-party sharing. See our privacy policy for details."
            />
            <PromiseCard
              icon="Check"
              title="Unsubscribe at any time"
              body="Reply to support@pdfcraftai.com with the word 'remove' and we'll delete your row before launch day. No link-chasing, no dark patterns."
            />
          </div>
        </div>
      </section>

      {/* ===== Already-supported visitor fallback ===== */}
      <section style={{ paddingTop: 56, paddingBottom: 120 }}>
        <div
          className="container-x"
          style={{ padding: "0 28px", maxWidth: 780 }}
        >
          <div
            className="card"
            style={{
              padding: 20,
              display: "flex",
              gap: 14,
              alignItems: "flex-start",
              background: "var(--bg-2)",
            }}
          >
            <span
              aria-hidden
              style={{
                width: 32,
                height: 32,
                borderRadius: 8,
                background: "var(--accent-soft)",
                color: "var(--accent)",
                display: "grid",
                placeItems: "center",
                flexShrink: 0,
              }}
            >
              <I.Info size={14} />
            </span>
            <div style={{ fontSize: 13, lineHeight: 1.6 }}>
              <div style={{ fontWeight: 500, marginBottom: 4 }}>
                Your country isn&apos;t in the picker?
              </div>
              <p className="muted" style={{ margin: 0 }}>
                It means we&apos;re already live there. You can{" "}
                <Link
                  href="/register"
                  style={{ color: "var(--accent)" }}
                >
                  create your account
                </Link>{" "}
                and start using the tools right now — no waiting. If
                something still blocks checkout, email{" "}
                <a
                  href="mailto:support@pdfcraftai.com"
                  className="mono"
                  style={{ color: "var(--accent)" }}
                >
                  support@pdfcraftai.com
                </a>{" "}
                and we&apos;ll look at it.
              </p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}

function PromiseCard({
  icon,
  title,
  body,
}: {
  icon: keyof typeof I;
  title: string;
  body: string;
}) {
  const Ic = I[icon];
  return (
    <div className="card" style={{ padding: 20 }}>
      <div
        style={{
          width: 36,
          height: 36,
          borderRadius: 8,
          background: "var(--accent-soft)",
          color: "var(--accent)",
          display: "grid",
          placeItems: "center",
          marginBottom: 12,
        }}
      >
        <Ic size={18} />
      </div>
      <div style={{ fontSize: 15, fontWeight: 500, marginBottom: 6 }}>
        {title}
      </div>
      <div className="muted" style={{ fontSize: 13, lineHeight: 1.55 }}>
        {body}
      </div>
    </div>
  );
}
