// lib/agent/types.ts
//
// Shared types for the production Agent mode (H1 onwards). The pre-existing
// /agent demo surface has its own AgentPlan in lib/workflow/agent-plan.ts
// — that's a deterministic-mock shape used by the public client-side demo.
// THESE types are for the real LLM-planned, server-executed agent that
// authenticated users get. We keep them in a separate namespace so the
// client-side demo can keep working unchanged while the new backend rolls
// out incrementally.

import type { AIOp } from "@/lib/ai/router";

/**
 * Identifier for any tool the agent can call. Three families:
 *   - "ai-*" → an existing AI op route (/api/ai/<op>)
 *   - non-AI tool ID from lib/tools.ts (e.g. "merge", "split") → free
 *     server-side WASM execution via a Node.js shim
 *   - "sys.*" → system primitive (fs.list, ask.user, notify.user)
 */
export type ToolName = string;

/**
 * Risk classification — drives the approval gate.
 *
 *   - "safe"     → run without confirmation (read-only ops, file processing)
 *   - "review"   → show a summary + Approve button before running
 *                  (cost > threshold, AI generation, irreversible file edits)
 *   - "dangerous" → REQUIRE explicit Approve before running
 *                  (email.send, slack.post, fs.move to user-shared paths,
 *                   anything that touches an external system)
 */
export type RiskLevel = "safe" | "review" | "dangerous";

/**
 * One step in an agent plan. Generated by the planner LLM, executed by
 * the executor. The shape is identical at plan-time and run-time so the
 * UI can render both with the same component.
 */
export interface AgentStep {
  /** Stable position in the plan (1-indexed for human-readable logs). */
  idx: number;
  /** Tool to invoke. Must exist in the agent tool registry. */
  tool: ToolName;
  /** Per-tool parameters. Schema enforced by the registry's Zod shape. */
  params: Record<string, unknown>;
  /** 3-7 word label rendered in the timeline ("OCR 12 receipts"). */
  label: string;
  /** Longer human-readable explanation, shown on hover / expand. */
  description: string;
  /**
   * Estimated cost in credits. Free / WASM tools have 0. Per-page /
   * per-Q AI tools include their best estimate based on inferred size
   * (planner reasons about page count from prior step output).
   */
  estCredits: number;
  /** Risk level — drives the approval gate. See `RiskLevel` doc. */
  risk: RiskLevel;
  /**
   * IDs of prior steps whose output this step consumes. The executor
   * reads each ID's output_ref from agent_run_steps and threads it
   * into params before invoking the tool.
   */
  dependsOn: number[];
}

/**
 * A complete plan, before execution. Persisted on the run record so it
 * can be reviewed, edited, replayed, or saved as a macro.
 */
export interface AgentPlan {
  /** What the user typed. Stored verbatim for audit + macro replay. */
  prompt: string;
  /** The ordered step list. */
  steps: AgentStep[];
  /** Sum of estCredits across all steps. */
  totalEstCredits: number;
  /** Predicted final output type (drives the "you'll get a .docx" preview). */
  output: {
    type: "pdf" | "docx" | "xlsx" | "zip" | "csv" | "txt" | "md";
    description: string;
    /**
     * Suggested filename including extension (H7.2). Optional —
     * pre-H7.2 plans don't have it and the UI falls back to the
     * legacy "Result.<type>" placeholder.
     */
    name?: string;
  };
  /** Plan-level confidence (0-1) returned by the planner LLM. */
  confidence: number;
  /** Anything the planner LLM wants the user to know before approving. */
  notes?: string[];
}

/**
 * Status of a run-step. Status diagram:
 *
 *     pending ──► running ──► succeeded
 *         │           │
 *         │           └─► failed
 *         └─► skipped (when a prior step failed and there's no recovery path)
 *         └─► awaiting_approval (when risk = "dangerous" and approval not pre-granted)
 */
export type StepStatus =
  | "pending"
  | "awaiting_approval"
  | "running"
  | "succeeded"
  | "failed"
  | "skipped";

/**
 * Status of an entire run.
 *
 *   - "queued"             → row created, executor not started yet
 *   - "running"            → at least one step has started
 *   - "awaiting_approval"  → executor paused on a dangerous step
 *   - "completed"          → all steps reached a terminal state, at least one succeeded
 *   - "failed"             → first step failed and no successor could run
 *   - "cancelled"          → user clicked Stop before completion
 */
export type RunStatus =
  | "queued"
  | "running"
  | "awaiting_approval"
  | "completed"
  | "failed"
  | "cancelled";

/**
 * Provider-agnostic op key. Subset of AIOp restricted to ops that make
 * sense to call from the agent. Excludes "chat" (interactive, not a
 * fire-and-forget tool) and "compare" (requires two inputs — handled
 * specially in the executor).
 */
export type AgentAiOp = Exclude<AIOp, "chat">;
